name: Package release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: |
          cd jarvis_sdk_node
          npm install
      - name: "Build"
        run: |
          cd jarvis_sdk_node
          npm run build
      - name: "Verify es support of dist package"
        run: |
          cd jarvis_sdk_node
          npm run-script check-es
      
      - name: "Copy README for publish"
        run: |
          cp ./README.md jarvis_sdk_node/
      - name: "Publish the package"
        run: |
          cd jarvis_sdk_node
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
